#!/bin/sh
#
# A hook script for the post-receive event
# It checks out the source to the working dir
# It neeeds the following config: receive.denyCurrentBranch = warn

# To keep a separate working directory just add the following config:
# [core]
#     bare = false
#     worktree = /webroot/dir/for/this/repo

DEBUG=$(git config hooks.debug)
if [ -n "$DEBUG" ]; then
	set -x
fi

# quit if bare
if [ $(git config core.bare) == "true" ]; then
	exit 0
fi

export GIT_DIR=$(pwd)

WORK_DIR=$(git config core.worktree)
if [ -n "$WORK_DIR" ]; then
	export GIT_WORK_TREE="$WORK_DIR"
else
	export GIT_WORK_TREE=".."
fi

cd "$GIT_WORK_TREE"
git --git-dir="$GIT_DIR" reset --hard HEAD

echo "repo updated at '$(pwd)'"
