#!/bin/sh
#
# A hook script for the post-receive event
# It pushes changes downstream

DOWNSTREAM_REMOTE="origin"
DOWNSTREAM_BRANCH="master"

DEBUG=$(git config hooks.debug)
if [ -n "$DEBUG" ]; then
	set -x
fi

DOWNSTREAM_PATH=$(git config hooks.downstream)

if [ -z "$DOWNSTREAM_PATH" ]; then
	echo "hooks.downstream not set. Quiting."
	exit 1
fi

cd "$DOWNSTREAM_PATH"
export GIT_DIR="$DOWNSTREAM_PATH/.git"
export GIT_WORK_TREE="$DOWNSTREAM_PATH"

git pull --ff-only $DOWNSTREAM_REMOTE $DOWNSTREAM_BRANCH

echo "repo pushed down to $DOWNSTREAM_PATH!"

